### ISSUE TITLE
Persistent Query no longer working - SDK aem-sdk-quickstart-2021.5.5309.20210515T190734Z-210429

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-guides-wknd-graphql#29]
### Expected Behavior
Application should load a list of Adventures based on a persistent query.

### Actual Behavior

Error: ServletError: Internal Servlet Failure

![image](https://user-images.githubusercontent.com/8974514/119412132-4b5b5c80-bca0-11eb-912a-1057464ced7c.png)

The issue seems that persistent queries are tied to a project specific endpoint...

### Reproduce Scenario (including but not limited to)
1. Use latest AEM SDK
2. Install WKND 0.3.0 - https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-0.3.0
3. Run the GraphQL app

**Comment by godanny86** [comment]
Interim fix is to manually enable the WKND endpoint:

1. Navigate to **Tools** > **Assets** > **GraphQL**
2. Create a new endpoint for WKND Site using the UI:

![image](https://user-images.githubusercontent.com/8974514/119416804-4d75e900-bca9-11eb-9104-3149333987f1.png)

**Comment by gknobloch** [comment]
It would probably make sense to also introduce an integration test that would validate this doesn't break upon upgrade.
