### ISSUE TITLE
Remote SPA Error on NPM Start

### ISSUE THREAD

**Issue by jhuangsoftware** [adobe/aem-guides-wknd-graphql#35]
#### Platform and Version
aem-sdk-2021.6.5382.20210602T190018Z-210527
aem-guides-wknd.all-1.0.0.zip
wknd-app.all-1.0.0-SNAPSHOT.zip
wknd-app.ui.content.sample-1.0.0.zip

### NPM Start Error
> aem-guides-wknd-app@0.1.0 start
> react-scripts start

Unexpected token '<<'

### Additional Information
AEM instance works with React sample app.

**Comment by SachinMali** [comment]
Closing this as no further updates were received. However, please see the updated tutorial @ https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/spa-editor/remote-spa/overview.html and ...feature/spa-editor [branch](https://github.com/adobe/aem-guides-wknd-graphql/tree/feature/spa-editor) of this project..
