### ISSUE TITLE
Static Node Server Error

### ISSUE THREAD

**Issue by charronadobe** [adobe/aem-guides-wknd-graphql#44]
From
https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/multi-step/production-deployment.html?lang=en#static-server

### Expected Behavior
serve starts on port 5000, serves content from running localhost:4503

### Actual Behavior
serve starts on port 3000, error loading page on localhost:3000
"Error: SyntaxError: Unexpected token < in JSON at position 0"

#### Steps to Reproduce
in VSCode aem-guides-wknd-graphql project, ./react-app:
npm install serve --save-dev
update package.json ("scripts") with
"serve": "npm run build && serve -s build"
In a browser, localhost:3000

**Comment by godanny86** [comment]
@charronadobe and you are starting the app with the command

```
npm run serve
```

Were you able to install the WKND Reference site on the publish environment? What version of AEM? AEM CS SDK?

Finally I would inspect the `crx-quickstart/logs/error.log` for the aem publish instance. When you see `Error: SyntaxError: Unexpected token < in JSON at position 0` it basically means that there is some issue with the connection with the AEM instance.

**Comment by charronadobe** [comment]
Hi @Daniel ***@***.***>,

I ran the entire tutorial again from scratch, same result on npm run serve (in a VSC terminal in the react-app directory of the mvn project (latest pull, tutorial/react branch)

***@***.***

Indeed I did install the latest version of
https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-1.0.0
on a publish instance of CS SKD 2021.10.5977.20211021T153528Z-210900
Everything looks fine there

Suggestions?



[signature_1318154851]
Andy Charron, MA, PMP, ECMP
905.237.7309 (office)
Adobe Experience Cloud
Senior Solution Consultant
647.401.1613 (mobile)
Adobe. Make It an Experience.
***@***.******@***.***>
www.adobe.com






From: Daniel Gordon ***@***.***>
Reply-To: adobe/aem-guides-wknd-graphql ***@***.***>
Date: Wednesday, November 10, 2021 at 13:56
To: adobe/aem-guides-wknd-graphql ***@***.***>
Cc: Andy Charron ***@***.***>, Mention ***@***.***>
Subject: Re: [adobe/aem-guides-wknd-graphql] Static Node Server Error (Issue #44)


@charronadobe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcharronadobe&data=04%7C01%7Ccharron%40adobe.com%7Cfa9a9042a80f45a6f06d08d9a47bc0b2%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637721673717307530%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4oOoSs4asKixbY%2BKlIZLR2xKr5UvmPsh4JmrkqMAS%2F8%3D&reserved=0> and you are starting the app with the command

npm run serve

Were you able to install the WKND Reference site on the publish environment? What version of AEM? AEM CS SDK?

Finally I would inspect the crx-quickstart/logs/error.log for the aem publish instance. When you see Error: SyntaxError: Unexpected token < in JSON at position 0 it basically means that there is some issue with the connection with the AEM instance.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadobe%2Faem-guides-wknd-graphql%2Fissues%2F44%23issuecomment-965643930&data=04%7C01%7Ccharron%40adobe.com%7Cfa9a9042a80f45a6f06d08d9a47bc0b2%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637721673717317525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dNRmjP%2FPxCzZYYzXnVe%2B%2FdqqiOqaNYX93P61gJaY0DE%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARVATQUUP65T7VXDAK2KWL3ULK54LANCNFSM5HMPDI4A&data=04%7C01%7Ccharron%40adobe.com%7Cfa9a9042a80f45a6f06d08d9a47bc0b2%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637721673717327520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QUf0ifBN6TlVBqJ3DMTQFzp9sthaRrpPFeneCpa2ygA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccharron%40adobe.com%7Cfa9a9042a80f45a6f06d08d9a47bc0b2%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637721673717327520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2X6ktaJIdZOcQ1vaNGCSGHBvWLMElz47zwBpDeRLEkY%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccharron%40adobe.com%7Cfa9a9042a80f45a6f06d08d9a47bc0b2%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637721673717337513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oRATPzjGu2vJvx70X6IdPbo%2FpMsYSDauBHpD2f%2F8sxc%3D&reserved=0>.
