### ISSUE TITLE
Avoid use of global endpoint

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-guides-wknd-graphql#48]
### Expected Behavior

The code samples should follow best practices and avoid use of the global endpoint for queries.

Instead of: `/content/graphql/global/endpoint.json` ->  `/content/cq:graphql/wknd/endpoint` should be used.

### Actual Behavior

Current samples were created prior to the creation of project specific endpoints and use the global endpoint.

**Comment by SachinMali** [comment]
@godanny86 & @davidjgonzalez  I think we can close this issue now since persisted queries are used and project-specific endpoint vs global endpoint..

**Comment by SachinMali** [comment]
Team, closing this as we have removed to '/content/graphql/global/endpoint.json'
