### ISSUE TITLE
Getting Error: QueryValidationError: Persisted Query Validation Error

### ISSUE THREAD

**Issue by malasanibalu** [adobe/aem-guides-wknd-graphql#49]
I am getting "Error: QueryValidationError: Persisted Query Validation Error" when accessing npm server.

![image](https://user-images.githubusercontent.com/19186532/154053803-a9f6d880-4894-49d2-ae58-bb6ca8d7c411.png)

Environment: AEM 6.5.10

Wknd site: aem-guides-wknd.all-1.1.0-classic.zip

**Comment by malasanibalu** [comment]
This issue resolved after restarting server post SP10 installation.

**Comment by godanny86** [comment]
Thanks @malasanibalu let us know if you run into any other issues!

**Comment by srikanta72** [comment]
![image](https://github.com/adobe/aem-guides-wknd-graphql/assets/25590140/d758ac7f-3034-44cd-b11c-5899b81c9e08)
 I am getting this error even after installing AEM 6.5 SP10 with restart. 
 @malasanibalu Please confirm in case you have done any additional step.

**Comment by srikanta72** [comment]
This is resolved:
There was some issue in my existing instance and I tried with a fresh instance(6.5.0), AEM SP18 package, WKND guides package. 
And it started working. 
I can check in the graphiQL Editor the queries were success.
