### ISSUE TITLE
tutorial/react not working with aem-guides-wknd 2.0.1-snapshot

### ISSUE THREAD

**Issue by deltaworld** [adobe/aem-guides-wknd-graphql#57]
### Expected Behavior
To display the content based on the content fragments in aem-guides-wknd

### Actual Behavior
No content is being displayed with an error
`Error: SyntaxError: Unexpected end of JSON input`

#### Steps to Reproduce
Follow the instructions based on the GraphQL > Quick Setup > Local SDK with latest AEM SDK
https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/quick-setup/local-sdk.html?lang=en

#### Platform and Version
MacOS 12.4
Oraclle Java version "11.0.15.1" 2022-04-22 LTS
Node.js v18.4.0
npm 8.13.1
Adobe Experience Manager 2022.6.7904.20220629T070041Z-220600 LocalSDK
aem-guides-wknd version 2.0.1-snapshot

#### Sample Code that illustrates the problem
```
 {
    adventureList {
      items {
        _path
        adventureTitle
        adventurePrice
        adventureTripLength
        adventurePrimaryImage {
          ... on ImageRef {
            _path
            mimeType
            width
            height
          }
        }
      }
    }
  }
```
```http://localhost:3000/content/cq:graphql/wknd-shared/endpoint.json```
The fieldlabels and endpoints have changed in 2.0.0 from 1.1.0 in aem-guides-wknd and has broken the headless app

**Comment by SachinMali** [comment]
Hello @deltaworld, we recently updated the tutorial to use persisted GraphQL queries and performed content restructuring, can you please re-try and let us know. Also, there is a basic GraphQL tutorial to understand, learn headless capabilities 

https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/multi-step/overview.html?lang=en
