### ISSUE TITLE
React App in /feature/spa-editor branch is not compatible anymore

### ISSUE THREAD

**Issue by akaash2512** [adobe/aem-guides-wknd-graphql#70]
As per Adobe tutorial to use remote SPA here  [https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/spa-editor/remote-spa/quick-setup.html?lang=en]

I tried to use "/feature/spa-editor" branch of this repo, which seems obsolete now.
I am using below packages on AEM (latest sdk):
aem-guides-wknd.all-2.0.0.zip
wknd-app.all-1.0.0-SNAPSHOT.zip
wknd-app.ui.content.sample-1.0.0.zip

Is there any app in this repo which is compatible with remote SPA feature?

**Comment by SachinMali** [comment]
We tested and that's correct it's broken after the recent WKND refactoring, we will prioritize it soon and fix it.

**Comment by SachinMali** [comment]
@akaash2512  this issue has been fixed, however, the tutorial instructions @ https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/spa-editor/remote-spa/quick-setup.html will be updated soon. 

Meanwhile please use below and let us know if you come across issue

**PreReq**
1.  Latest AEM SDK
2. Node 16+
3. NPM 8+

**Steps**

- Install Below Packages

1. [aem-guides-wknd.all-2.1.0.zip](https://github.com/adobe/aem-guides-wknd/releases/download/aem-guides-wknd-2.1.0/aem-guides-wknd.all-2.1.0.zip)
2. [wknd-app.all-1.0.0-SNAPSHOT.zip](https://experienceleague.adobe.com/docs/experience-manager-learn/assets/wknd-app.all-1.0.0-SNAPSHOT.zip?lang=en)
3. [wknd-app.ui.content.sample-1.0.1.zip](https://github.com/adobe/aem-guides-wknd-graphql/files/9340047/wknd-app.ui.content.sample-1.0.1.zip)

- Clone https://github.com/adobe/aem-guides-wknd-graphql/tree/feature/spa-editor 
- Goto `react-app` dir
- Run 
```code
$ npm install
$ npm start
``` 

You should see Remote SPA loading at http://localhost:3000/ and AEM SPA ediatble page @ http://localhost:4502/editor.html/content/wknd-app/us/en/home.html

**Comment by SachinMali** [comment]
Also, the tutorial content/instructions have been updated, see https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/spa-editor/remote-spa/overview.html. Please re-open issue if you come across anything else..
